site_name: Kwiscale manual
site_author: Patrice FERLET
site_url: http://kwiscale.io
repo_url: https://github.com/kwiscale/framework
theme: readthedocs
pages:
    - Home: index.md
    - Getting started: gettingstarted.md
    - Developping: 
        - Information: develop/generalities.md
        - Common project structure: develop/structure.md
        - RequestHandler: develop/requesthandler.md
        - WebSocketHandler: develop/websockethandler.md
    - Templating:
        - Introduction: templates/intro.md
        - Built-in template engine: templates/built-in.md
        - Pongo2 template engine: templates/pongo2.md
      
